TRUNCATE TABLE users CASCADE;
ALTER TABLE users ADD COLUMN email VARCHAR(255) NOT NULL UNIQUE;
ALTER TABLE users ADD COLUMN password_hash VARCHAR(255) NOT NULL;
ALTER TABLE users ADD COLUMN role VARCHAR(50) NOT NULL DEFAULT 'member';